# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  servlet:
    context-path: /generator


spring:
  profiles:
    active: config
  datasource:
    # Oracle连接
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ip:port/database
    username: root
    password: 123456
    # MySQL 连接
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://ip:port/database?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
