properties:
  config:
    # 主路径
    mainPath: org.generator.modules
    # 模块包路径
    package: com.dawn.rockcandy.modules
    # 模块名称
    moduleName: demo
    # 作者
    author: tangzedong
    # Email
    email: tangzedong.programmer@gmail.com
    # 需要过滤的表前缀，多行以逗号分隔开
    tablePrefix: t_
    # 需要过滤的列前缀，多行以逗号分隔开
    columnPrefix: c_
    # 文件输出路径
    fileOutputPaht: D:\demo
    # 是否使用swagger注解，默认为true，会在Domain以及Controller层加上swagger相关注解
    useSwagger: ture
    # 是否使用shiro安全校验注解，默认为false，会在controller层上加上shiro相关注解
    useShiro: false
    # 需要生成代码的数据库表名称，多表以逗号分隔开，不能为空
    generatorTableName: tableName
